In [3]:
#Write a NumPy program to compute the mean, standard deviation, and variance of a given array along the second axis. 
#Go to the editor
#Sample output:
#Original array:
#[0 1 2 3 4 5]
#Mean: 2.5
#std: 1
#variance: 2.916666666666666
import numpy as np
arr=np.array([0,1,2,3,4,5])
mean = np.mean(arr)
std= np.std(arr)
var=np.var(arr)
print("Original array:\n",arr)
print("Mean:\n",mean)
print("std:\n",std)
print("variance:\n",var)


Original array:
 [0 1 2 3 4 5]
Mean:
 2.5
std:
 1.707825127659933
variance:
 2.9166666666666665


In [7]:
#Write a NumPy program to compute the weighted of a given array. Go to the editor
#Sample Output:
#Original array:
#[0 1 2 3 4]
#Weighted average of the said array:
#2.6666666666666665

sample=np.array([0,1,2,3,4])
mean=np.mean(sample)
print("Original array:\n",sample)
print("Mean:\n",mean)

Original array:
 [0 1 2 3 4]
Mean:
 2.0


In [20]:
import numpy as np

# Original array
array = np.array([0, 1, 2, 3, 4])

# Weights for each element
weights = np.array([1, 2, 3, 4, 5])

# Compute the weighted average
weighted_average = np.average(array, weights=weights)

# Print the results
print("Original array:")
print(array)
print("\nWeights:")
print(weights)
print("\nWeighted average of the said array:")
print(weighted_average)



Original array:
[0 1 2 3 4]

Weights:
[1 2 3 4 5]

Weighted average of the said array:
2.6666666666666665


In [17]:
array = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])


In [18]:
# Compute mean along the second axis (axis=1)
mean_along_second_axis = np.mean(array, axis=1)

# Compute standard deviation along the second axis (axis=1)
std_dev_along_second_axis = np.std(array, axis=1)

# Compute variance along the second axis (axis=1)
variance_along_second_axis = np.var(array, axis=1)


In [19]:
# Print results
print("Array:")
print(array)
print("\nMean along the second axis:")
print(mean_along_second_axis)
print("\nStandard deviation along the second axis:")
print(std_dev_along_second_axis)
print("\nVariance along the second axis:")
print(variance_along_second_axis)

Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Mean along the second axis:
[ 2.5  6.5 10.5]

Standard deviation along the second axis:
[1.11803399 1.11803399 1.11803399]

Variance along the second axis:
[1.25 1.25 1.25]


In [13]:
#Write a Python program to set a random seed and get a random number between 0 and 1
np.random.seed(6)
np.random.rand(10)

array([0.89286015, 0.33197981, 0.82122912, 0.04169663, 0.10765668,
       0.59505206, 0.52981736, 0.41880743, 0.33540785, 0.62251943])

In [11]:
#Write a Python program to generate a series of distinct random numbers.
np.random.randn(10)

array([ 0.18760323, -0.32986996, -1.19276461, -0.20487651, -0.35882895,
        0.6034716 , -1.66478853, -0.70017904,  1.15139101,  1.85733101])

In [146]:
#Write a NumPy program to generate six random integers between 10 and 30. Go to the editor
#Expected Output:
#[20 28 27 17 28 29]
x=np.random.randint(10,30,(1,6))
x

array([[22, 27, 25, 24, 19, 28]])

In [153]:
#Write a NumPy program to create a 3x3x3 array with random values
y=np.random.randint(1,10,(3,3))
y

array([[7, 9, 2],
       [6, 3, 3],
       [5, 9, 8]])

In [2]:
#Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values
import numpy as np
z=np.random.randint(1,30,(5,5))
z

array([[10, 11, 11,  1,  4],
       [ 5, 17, 18, 13, 10],
       [25, 15, 22, 25, 23],
       [14, 22, 23,  6, 12],
       [ 5, 16,  7, 11, 13]])