In [1]:
import numpy as np

In [2]:
data=np.array([1,2,3,4,5])

In [3]:
data

array([1, 2, 3, 4, 5])

In [4]:
print(data)

[1 2 3 4 5]


In [5]:
print(data[1:4])

[2 3 4]


In [6]:
print(data[::-1])

[5 4 3 2 1]


In [7]:
data[1]

np.int64(2)

In [8]:
print(data[1])

2


In [9]:
data = np.array([1, 2, np.nan, 4, 5])

In [10]:
print(np.isnan(data))

[False False  True False False]


In [12]:
c=data[~np.isnan(data)]

In [13]:
c

array([1., 2., 4., 5.])

In [14]:
print(c)

[1. 2. 4. 5.]
